In [3]:
import numpy as np

In [ ]:
# 75. How to compute averages using a sliding window over an array? (★★★)

In [51]:
arr = np.arange(5)

In [53]:
arr

array([0, 1, 2, 3, 4])

In [57]:
wind = np.lib.stride_tricks.sliding_window_view(arr, window_shape = 2)
wind

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4]])

In [59]:
np.mean(wind, axis = 1)

array([0.5, 1.5, 2.5, 3.5])

In [61]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is 
#     (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [79]:
Z = np.arange(12)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
np.reshape(Z, (-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [85]:
bool_arr = np.array([True, True, False, True])
bool_arr

array([ True,  True, False,  True])

In [87]:
~bool_arr

array([False, False,  True, False])

In [89]:
float_arr = np.array([-0.43, 0.89])
float_arr

array([-0.43,  0.89])

In [95]:
float_arr * (-1)

array([ 0.43, -0.89])

In [ ]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [251]:
arr_3_dem = np.random.randint(0,5, (5,5,3))
arr_2_dem = np.random.randint(0,5, (5,5))
print(arr_3_dem)
print(arr_2_dem)

[[[2 2 3]
  [3 2 4]
  [4 3 4]
  [0 4 3]
  [1 2 2]]

 [[2 3 3]
  [4 1 1]
  [1 4 3]
  [3 1 1]
  [3 4 4]]

 [[2 4 0]
  [4 1 2]
  [3 4 1]
  [4 2 3]
  [4 1 2]]

 [[0 2 2]
  [3 0 3]
  [1 2 0]
  [0 1 0]
  [3 2 1]]

 [[2 4 0]
  [1 4 3]
  [2 3 2]
  [0 4 3]
  [3 3 3]]]
[[1 1 0 1 1]
 [4 1 4 4 3]
 [2 3 4 0 0]
 [3 1 3 4 2]
 [3 2 1 3 4]]


In [261]:
reshaped_arr_2_dem = arr_2_dem[:,:,np.newaxis]
print(np.shape(reshaped_arr_2_dem ))
print(reshaped_arr_2_dem)

(5, 5, 1)
[[[1]
  [1]
  [0]
  [1]
  [1]]

 [[4]
  [1]
  [4]
  [4]
  [3]]

 [[2]
  [3]
  [4]
  [0]
  [0]]

 [[3]
  [1]
  [3]
  [4]
  [2]]

 [[3]
  [2]
  [1]
  [3]
  [4]]]


In [265]:
result = reshaped_arr_2_dem * arr_3_dem
result

array([[[ 2,  2,  3],
        [ 3,  2,  4],
        [ 0,  0,  0],
        [ 0,  4,  3],
        [ 1,  2,  2]],

       [[ 8, 12, 12],
        [ 4,  1,  1],
        [ 4, 16, 12],
        [12,  4,  4],
        [ 9, 12, 12]],

       [[ 4,  8,  0],
        [12,  3,  6],
        [12, 16,  4],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  6,  6],
        [ 3,  0,  3],
        [ 3,  6,  0],
        [ 0,  4,  0],
        [ 6,  4,  2]],

       [[ 6, 12,  0],
        [ 2,  8,  6],
        [ 2,  3,  2],
        [ 0, 12,  9],
        [12, 12, 12]]])

In [ ]:
# 69. How to get the diagonal of a dot product? (★★★)

In [233]:
i_A = 4
j_A = 5
A = np.random.randint(0,5, (i_A,j_A))
B = np.random.randint(0,5, (j_A,i_A))
print(A)
print(B)

[[3 3 0 4 0]
 [0 0 0 0 0]
 [2 0 1 4 0]
 [2 1 0 3 1]]
[[4 3 4 4]
 [2 1 1 2]
 [1 4 4 4]
 [0 1 4 4]
 [1 2 2 1]]


In [247]:
#for checking (get result of matrixes product)
np.einsum('ij,jk->ik',A,B)

array([[18, 16, 31, 34],
       [ 0,  0,  0,  0],
       [ 9, 14, 28, 28],
       [11, 12, 23, 23]])

In [245]:
np.einsum('ij,ji->i',A,B)

array([18,  0, 28, 23])

In [ ]:
#80. Consider an arbitrary array, write a function that extract a subpart with 
#a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [27]:
np.random.seed(seed= 42)
frst_arr = np.random.randint(1, 10, (4,4))
new_centr = (2,3)
shape = (3,3)
fill = 1
frst_arr

array([[7, 4, 8, 5],
       [7, 3, 7, 8],
       [5, 4, 8, 8],
       [3, 6, 5, 2]])

In [91]:
shape = np.array(shape)
new_centr = np.array(new_centr)
start_ind = np.maximum((2 * new_centr - shape + 1)//2, 0)
start_ind

array([1, 2])

In [93]:
end_ind = np.minimum((2 * new_centr + shape - 1)//2, shape)
end_ind

array([3, 3])

In [111]:
new_arr = np.full(shape, fill)

In [113]:
insert_start = np.maximum((shape-1 - (end_ind - start_ind)) // 2, 0)
insert_end = insert_start + (end_ind - start_ind)
new_arr[insert_start[0]:insert_end[0]+1, insert_start[1]:insert_end[1]+1] = frst_arr[start_ind[0]:end_ind[0] + 1, start_ind[1]:end_ind[1] + 1]
new_arr

array([[7, 8, 1],
       [8, 8, 1],
       [5, 2, 1]])

In [ ]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an 
#array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [117]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] 
shift = 4
R = np.array([Z[k: k+ shift] for k in range(len(Z) - shift + 1)])
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [ ]:
#82. Compute a matrix rank (★★★)

In [123]:
ar = np.array([[1,2,1], [-2,-3,1], [3,5,0]])
np.linalg.matrix_rank(ar)

2

In [ ]:
# 83. How to find the most frequent value in an array? (★★★)

In [129]:
arr = np.random.randint(3,5, (1, 10))
arr

array([[4, 4, 3, 4, 3, 3, 3, 3, 3, 4]])

In [131]:
unique_val, count_un_val = np.unique(arr, return_counts = True)
most_freq_val = unique_val[np.argmax(count_un_val)]
most_freq_val

3

In [ ]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [135]:
matr = np.random.randint(0,60, (10, 10))
matr

array([[ 4, 41, 38, 57, 40, 27,  6,  8,  7, 11],
       [33, 32, 47, 54, 22, 23, 36, 34, 43, 39],
       [21, 26, 34,  0, 34, 36, 46, 13,  2,  0],
       [ 4, 25, 54, 13, 38, 26,  8, 14, 14, 25],
       [41, 59, 12, 50, 31, 38, 48, 51, 31,  3],
       [29, 36, 22, 38, 44, 14, 42, 28, 35, 12],
       [31,  6, 58, 50, 21, 27,  1, 41, 44, 56],
       [52,  5, 27, 27, 43, 43, 19, 29, 10, 57],
       [54, 27, 24, 38, 32,  0, 56, 26, 56, 51],
       [12, 40,  2, 38,  5,  7, 26,  8, 36, 32]])

In [137]:
block = np.array([matr[i: i+3, j:j+3] for i in range(np.shape(matr)[0] - 2) for j in range(np.shape(matr)[0] - 2)])
block

array([[[ 4, 41, 38],
        [33, 32, 47],
        [21, 26, 34]],

       [[41, 38, 57],
        [32, 47, 54],
        [26, 34,  0]],

       [[38, 57, 40],
        [47, 54, 22],
        [34,  0, 34]],

       [[57, 40, 27],
        [54, 22, 23],
        [ 0, 34, 36]],

       [[40, 27,  6],
        [22, 23, 36],
        [34, 36, 46]],

       [[27,  6,  8],
        [23, 36, 34],
        [36, 46, 13]],

       [[ 6,  8,  7],
        [36, 34, 43],
        [46, 13,  2]],

       [[ 8,  7, 11],
        [34, 43, 39],
        [13,  2,  0]],

       [[33, 32, 47],
        [21, 26, 34],
        [ 4, 25, 54]],

       [[32, 47, 54],
        [26, 34,  0],
        [25, 54, 13]],

       [[47, 54, 22],
        [34,  0, 34],
        [54, 13, 38]],

       [[54, 22, 23],
        [ 0, 34, 36],
        [13, 38, 26]],

       [[22, 23, 36],
        [34, 36, 46],
        [38, 26,  8]],

       [[23, 36, 34],
        [36, 46, 13],
        [26,  8, 14]],

       [[36, 34, 43],
        [46, 13,  2],
    

In [ ]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [174]:
class Symmetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symmetric, self).__setitem__((i, j), value)
        super(Symmetric, self).__setitem__((j, i), value)
size = 6
Z = Symmetric((size, size)) 
Z[0, 1] = 20  
Z[2, 1] = 6  
Z

Symmetric([[ 0., 20.,  0.,  0.,  0.,  0.],
           [20.,  0.,  6.,  0.,  0.,  0.],
           [ 0.,  6.,  0.,  0.,  0.,  0.],
           [ 0.,  0.,  0.,  0.,  0.,  0.],
           [ 0.,  0.,  0.,  0.,  0.,  0.],
           [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [178]:
#86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). 
#How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [57]:
p = 3
n = 4

In [61]:
arr_matr = np.random.randint(0, 20,(p, n, n))
p = np.random.randint(0, 20,(p, n, 1))
print(arr_matr)
print(p)

[[[ 8 17  6 12]
  [ 7  0  5  5]
  [12 10  8 13]
  [ 5  9 17 11]]

 [[10  0  7 17]
  [ 3  3  0 15]
  [ 6  3  3 19]
  [ 6 15  0 10]]

 [[17 10  3  0]
  [ 6 12 15  6]
  [ 9 12 18  9]
  [18 18  5  2]]]
[[[14]
  [ 7]
  [ 8]
  [10]]

 [[15]
  [12]
  [ 0]
  [15]]

 [[16]
  [15]
  [ 4]
  [17]]]


In [87]:
result = np.tensordot(arr_matr, p, axes=[[0, 2], [0, 1]])
result

array([[1238],
       [ 932],
       [1392],
       [1411]])

In [ ]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [90]:
n = 16
shift = 4
A = np.random.randint(0,30, (n, n))
sum_block = np.array([np.sum(A[shift*i:shift*(i + 1),shift*j:shift*(j + 1)]) for i in range(n//shift) for j in range(n//shift)]).reshape((n//shift,n//shift))

In [92]:
print(A)
print(sum_block)

[[ 0  0 20  4  0 25 16 25  8  8  6 23  0 28 10 25]
 [ 1  7 19 17 13  9 22  9  7 26  5  0 10 10 23 18]
 [12 15 28 11 12 15  4 18  3 20 25 12  0 28 24  5]
 [ 3 12 20 10  2 19 19 28  4  8 22  4  5 26 13  0]
 [27  1 14  6  9  8 27  7  8  6 28 25 20 19  6 26]
 [20 12  9 29 21  6  1 10 28 26 26 26  1  3 17 12]
 [ 8 19 20 29 26 10 27 14 23 25 19 28  9 19  4 29]
 [15 13 20  5  1 23 21 15 23  8 18 15  8 11 24  3]
 [27  2  6 29  5  5 13 11 28  4 13 15  6 12  1  6]
 [14 22 19 18 12  8 16 29  5  3 18 28 24  3 21 26]
 [ 0 16  6  2 29 28 13 23 18  0 17 14 25 18  8 13]
 [ 4 22  9 20 13 25 29 24 26 13 24  7 23 22 21 15]
 [13  7  0  5 26  4 28 13 14 25 19  1 12  9 10  8]
 [ 5 20 24 15  7 21 13 27 10 27  8 18 12 24 12  6]
 [ 1 26 20  5 28 11 10 22 18  9  7 24  5  6 26  9]
 [16  3  7 15 25  3  0 24 24 19  1 25 29 13  3 27]]
[[179 236 181 225]
 [247 226 332 211]
 [216 283 233 244]
 [182 262 249 211]]


In [ ]:
#88. How to implement the Game of Life using numpy arrays? (★★★)

In [5]:
n = 4
A = np.random.randint(0, 2, (n, n))
changed_A = A.copy()
print("Previous")
print(A)
for i in range(np.shape(A)[0]):
    for j in range(np.shape(A)[1]):
        count_neigh = np.sum(A[max(0, i-1):min(i+2,np.shape(A)[0]),max(0, j-1):min(j+2,np.shape(A)[1])]) - A[i][j]
        if changed_A[i][j] == 1:
            if count_neigh < 2 or count_neigh > 3:
                changed_A[i][j] = 0
        elif count_neigh == 3:
            changed_A[i][j] = 1
print('changed_A')
print(changed_A)

Previous
[[1 0 0 1]
 [0 0 1 0]
 [0 1 1 1]
 [1 1 1 1]]
changed_A
[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [1 0 0 1]]


In [ ]:
# 89. How to get the n largest values of an array (★★★)

In [31]:
n = 4
ar = np.random.randint(0,89, (10,))
ar

array([15,  7, 48, 85, 16, 77, 52, 43, 65, 52])

In [42]:
index = np.argpartition(-ar, n)
print(ar[index][:n])

[65 85 77 52]


In [ ]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [78]:
n = 2
vect = np.random.randint(0, 28, (n, 2)) 
vect

array([[10, 11],
       [24, 18]])

In [106]:
transpose_arr = np.array(np.meshgrid(vect[0], vect[1])).T
new_trans = transpose_arr.reshape(-1, n)
new_trans

array([[10, 24],
       [10, 18],
       [11, 24],
       [11, 18]])

In [ ]:
## 91. How to create a record array from a regular array? (★★★)

In [132]:
data = np.array([
    ['Africa', 25.3],
    ['Japan', 70.5],
    ['Europe',68.2,]
])

[25.3 70.5 68.2]


In [142]:
separ_type_arr = [data[:, 0], data[:, 1].astype(float)]

In [154]:
record_arr = np.core.records.fromarrays(separ_type_arr, dtype = [('names', 'S20'), ('int_numb',np.int32)])
print(record_arr['names'])

[b'Africa' b'Japan' b'Europe']


In [ ]:
 #92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [172]:
Z = np.random.randint(0, 20, (400,))
Z

array([18, 18,  2,  1,  0, 12, 17, 14,  0, 12, 12,  9,  9,  3,  8,  9,  8,
        1, 19,  6, 11,  0, 14, 10, 18,  3,  2, 16, 16, 13,  5,  4, 12,  8,
       15, 17,  8,  8, 10,  0, 14,  6,  5,  0,  4, 13, 16, 15,  6,  2, 12,
        0, 10,  9, 16, 13, 13,  1, 18,  7, 10, 13, 12, 12, 18,  0, 11,  3,
        5, 17,  7, 14,  6,  3, 19,  7, 19,  4, 11,  7, 18,  9,  2, 16, 15,
       12,  1,  4, 19, 16, 13,  3, 18,  7,  9,  9, 16, 16, 16, 13,  5, 16,
        9,  0,  6, 19,  3, 10,  8,  7, 14, 13, 19, 19, 15, 14, 14,  2,  4,
        9, 18, 14, 15,  8,  9,  4, 19, 16,  3,  3,  2, 12,  9, 14, 14,  8,
       16, 17,  6, 10,  5, 10,  9, 14,  6, 19, 13, 12, 10,  0, 17,  2,  4,
        0, 13,  3,  0,  6, 10, 19,  0, 15, 15,  9,  6, 18, 10,  7,  0, 12,
        5, 13,  0, 19, 11, 17,  0, 16, 18,  4,  6, 14,  7, 13, 15, 14, 17,
       16, 15, 19,  5, 17,  0,  1,  7, 17,  0,  9,  6, 11,  0,  9, 10,  2,
       11,  1,  2,  8,  3,  8,  7,  6, 13, 11,  7, 19, 13, 16,  3, 19, 17,
        4, 14,  9,  2, 14

In [174]:
#method1
meth1_pow_arr = np.power(Z, 3)
meth1_pow_arr

array([5832, 5832,    8,    1,    0, 1728, 4913, 2744,    0, 1728, 1728,
        729,  729,   27,  512,  729,  512,    1, 6859,  216, 1331,    0,
       2744, 1000, 5832,   27,    8, 4096, 4096, 2197,  125,   64, 1728,
        512, 3375, 4913,  512,  512, 1000,    0, 2744,  216,  125,    0,
         64, 2197, 4096, 3375,  216,    8, 1728,    0, 1000,  729, 4096,
       2197, 2197,    1, 5832,  343, 1000, 2197, 1728, 1728, 5832,    0,
       1331,   27,  125, 4913,  343, 2744,  216,   27, 6859,  343, 6859,
         64, 1331,  343, 5832,  729,    8, 4096, 3375, 1728,    1,   64,
       6859, 4096, 2197,   27, 5832,  343,  729,  729, 4096, 4096, 4096,
       2197,  125, 4096,  729,    0,  216, 6859,   27, 1000,  512,  343,
       2744, 2197, 6859, 6859, 3375, 2744, 2744,    8,   64,  729, 5832,
       2744, 3375,  512,  729,   64, 6859, 4096,   27,   27,    8, 1728,
        729, 2744, 2744,  512, 4096, 4913,  216, 1000,  125, 1000,  729,
       2744,  216, 6859, 2197, 1728, 1000,    0, 49

In [176]:
#method2
meth2_pow_arr = Z**3
meth2_pow_arr

array([5832, 5832,    8,    1,    0, 1728, 4913, 2744,    0, 1728, 1728,
        729,  729,   27,  512,  729,  512,    1, 6859,  216, 1331,    0,
       2744, 1000, 5832,   27,    8, 4096, 4096, 2197,  125,   64, 1728,
        512, 3375, 4913,  512,  512, 1000,    0, 2744,  216,  125,    0,
         64, 2197, 4096, 3375,  216,    8, 1728,    0, 1000,  729, 4096,
       2197, 2197,    1, 5832,  343, 1000, 2197, 1728, 1728, 5832,    0,
       1331,   27,  125, 4913,  343, 2744,  216,   27, 6859,  343, 6859,
         64, 1331,  343, 5832,  729,    8, 4096, 3375, 1728,    1,   64,
       6859, 4096, 2197,   27, 5832,  343,  729,  729, 4096, 4096, 4096,
       2197,  125, 4096,  729,    0,  216, 6859,   27, 1000,  512,  343,
       2744, 2197, 6859, 6859, 3375, 2744, 2744,    8,   64,  729, 5832,
       2744, 3375,  512,  729,   64, 6859, 4096,   27,   27,    8, 1728,
        729, 2744, 2744,  512, 4096, 4913,  216, 1000,  125, 1000,  729,
       2744,  216, 6859, 2197, 1728, 1000,    0, 49

In [178]:
#method3
np.einsum('m,m,m->m', Z,Z,Z)

array([5832, 5832,    8,    1,    0, 1728, 4913, 2744,    0, 1728, 1728,
        729,  729,   27,  512,  729,  512,    1, 6859,  216, 1331,    0,
       2744, 1000, 5832,   27,    8, 4096, 4096, 2197,  125,   64, 1728,
        512, 3375, 4913,  512,  512, 1000,    0, 2744,  216,  125,    0,
         64, 2197, 4096, 3375,  216,    8, 1728,    0, 1000,  729, 4096,
       2197, 2197,    1, 5832,  343, 1000, 2197, 1728, 1728, 5832,    0,
       1331,   27,  125, 4913,  343, 2744,  216,   27, 6859,  343, 6859,
         64, 1331,  343, 5832,  729,    8, 4096, 3375, 1728,    1,   64,
       6859, 4096, 2197,   27, 5832,  343,  729,  729, 4096, 4096, 4096,
       2197,  125, 4096,  729,    0,  216, 6859,   27, 1000,  512,  343,
       2744, 2197, 6859, 6859, 3375, 2744, 2744,    8,   64,  729, 5832,
       2744, 3375,  512,  729,   64, 6859, 4096,   27,   27,    8, 1728,
        729, 2744, 2744,  512, 4096, 4913,  216, 1000,  125, 1000,  729,
       2744,  216, 6859, 2197, 1728, 1000,    0, 49

In [ ]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). 
#How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [184]:
np.random.seed(42)
A = np.random.randint(0,6, (8,3))
B = np.random.randint(0,8, (2,2))
result_arr = []
print(A)
print(B)

[[3 4 2]
 [4 4 1]
 [2 2 2]
 [4 3 2]
 [5 4 1]
 [3 5 5]
 [1 3 4]
 [0 3 1]]
[[5 4]
 [3 0]]


In [186]:
for i in range(np.shape(B)[0]):
    for j in range(np.shape(A)[0]):
        if all(np.count_nonzero(A[j] == elem) >= np.count_nonzero(B[i] == elem) for elem in B[i]):
            result_arr.append(A[j])
print(np.array(result_arr))

[[5 4 1]
 [0 3 1]]


In [ ]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [198]:
matrix = np.random.randint(0,20, (10,3))
print(matrix)
def find_unique_el(row_lst):
    return np.shape(np.unique(row_lst))[0] == np.shape(row_lst)[0]

check_unique = np.apply_along_axis(find_unique_el, 1, matrix)
non_unique_val_matr = matrix[~check_unique]
print(check_unique)
print(non_unique_val_matr)

[[17  7  3]
 [ 1  5  9]
 [ 3 17 11]
 [ 1  9  3]
 [13 15 14]
 [ 7 13  7]
 [15 12 17]
 [14 12  8]
 [14 12  0]
 [ 6  8  0]]
[ True  True  True  True  True False  True  True  True  True]
[[ 7 13  7]]


In [ ]:
# 95. Convert a vector of ints into a matrix binary representation (★★★)

In [7]:
vec_int = np.random.randint(0,34, (10,))
vec_int

array([27,  5,  2,  6, 16,  3, 17, 14,  0, 25])

In [11]:
np.binary_repr(vec_int[0])

'11011'

In [22]:
max_bits = max([x.bit_length() for x in vec_int.tolist()])
max_bits

5

In [40]:
binary_matr = np.array([np.array([np.binary_repr(i, width = max_bits)]) for i in vec_int], dtype = int)
binary_matr

array([[11011],
       [  101],
       [   10],
       [  110],
       [10000],
       [   11],
       [10001],
       [ 1110],
       [    0],
       [11001]])

In [ ]:
# 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [65]:
two_des_arr = np.random.randint(0,2, (3,3))
two_des_arr

array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [83]:
unique = np.unique(two_des_arr, axis = 0)
print(unique)

[[1 0 0]
 [1 1 1]]


In [ ]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [87]:
a_vect = np.random.randint(0,49, (5,))
b_vect = np.random.randint(0,10, (5,))
print(a_vect)
print(b_vect)

[26  7 37 45 31]
[5 5 8 4 2]


In [91]:
inner = np.einsum('i,i', a_vect, b_vect)
inner

703

In [229]:
outer = np.einsum('i,j->ij', a_vect, b_vect)
outer

array([[130, 130, 208, 104,  52],
       [ 35,  35,  56,  28,  14],
       [185, 185, 296, 148,  74],
       [225, 225, 360, 180,  90],
       [155, 155, 248, 124,  62]])

In [113]:
sum_A = np.einsum('i->', a_vect)
sum_A

146

In [117]:
sum_B = np.einsum('i->', b_vect)
sum_B

24

In [231]:
mult = np.einsum('i,i->i', a_vect, b_vect)
mult

array([130,  35, 296, 180,  62])

In [ ]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [203]:
arr_four_dimen = np.random.randint(0,5, (4, 2, 3, 5))
arr_four_dimen

array([[[[1, 0, 4, 0, 3],
         [3, 4, 0, 4, 3],
         [2, 0, 1, 1, 4]],

        [[0, 1, 3, 3, 2],
         [2, 3, 1, 4, 3],
         [4, 4, 0, 1, 4]]],


       [[[0, 3, 2, 3, 2],
         [0, 1, 1, 1, 0],
         [2, 4, 4, 4, 3]],

        [[4, 3, 3, 3, 1],
         [0, 2, 1, 4, 1],
         [4, 3, 2, 4, 2]]],


       [[[0, 3, 1, 4, 2],
         [3, 2, 4, 3, 2],
         [2, 2, 0, 4, 4]],

        [[2, 0, 4, 4, 0],
         [4, 3, 1, 4, 3],
         [1, 2, 4, 1, 4]]],


       [[[3, 3, 3, 4, 3],
         [4, 2, 3, 1, 0],
         [1, 3, 3, 1, 2]],

        [[2, 1, 3, 1, 1],
         [0, 1, 0, 0, 3],
         [0, 1, 3, 4, 1]]]])

In [209]:
np.sum(arr_four_dimen,axis = (-2,-1))

array([[30, 35],
       [30, 37],
       [36, 37],
       [36, 21]])

In [ ]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution 
#with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [159]:
# arr_2_dem = np.random.randint(0,8, (5,4))
arr_2_dem = np.array([[6, 3, 0, 0],[0, 5, 2, 2],[4, 2, 6, 7],[3, 6, 5, 3],[0, 0, 3, 7]])
print(arr_2_dem)

[[6 3 0 0]
 [0 5 2 2]
 [4 2 6 7]
 [3 6 5 3]
 [0 0 3 7]]


In [ ]:
n = 9

In [169]:
arr_2_dem[arr_2_dem.sum(axis = 1) == 9]

array([[6, 3, 0, 0],
       [0, 5, 2, 2]])

In [ ]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X 
#(i.e., resample the elements of an array with replacement N times, compute the mean of each sample, 
#and then compute percentiles over the means). (★★★)

In [183]:
X_arr = np.random.randint(0,34, (10))
N = 8
X_arr

array([17, 18, 28, 33,  7, 15,  5, 33, 33,  0])

In [187]:
bootstrapp = np.array([np.random.choice(X_arr, size = np.shape(X_arr)[0], replace=True) for _ in range(N)])
bootstrapp

array([[ 7, 18, 15,  0, 17,  5, 33, 17,  5, 33],
       [33, 33, 33, 33, 33, 33,  0, 33,  5, 33],
       [28, 17,  7, 33, 33,  5, 15,  0, 15, 15],
       [17, 15, 28,  7, 33, 17, 17,  0, 28,  0],
       [17, 33,  0, 33, 18,  7,  5,  7,  7, 15],
       [28,  0,  0, 33, 17, 28, 18, 17, 15,  0],
       [ 5, 17,  5, 17,  5,  5,  7, 15, 15, 28],
       [ 5, 28, 17, 33, 17, 15, 18, 17, 33, 33]])

In [193]:
mean_bootstr = np.mean(bootstrapp, axis = 1)

In [197]:
conf_interv = np.percentile(mean_bootstr, [2.5, 97.5])
conf_interv

array([12.3025, 25.9725])